version: "3.6"
services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      POSTGRES_DB: root
    volumes:
      - type: volume
        source: postgres
        target: /var/lib/postgresql/data

  redis:
    image: redis:6

  app:
    image: node:17-alpine
    working_dir: "/app"
    user: node
    command: "yarn dev -c /app/config.dev.json"
    volumes:
      - type: bind
        source: ./
        target: /app
      - type: bind
        source: ./data
        target: /data
    ports:
      - 0.0.0.0:10006:10006
    environment:
      COMMON_DATABASE_URL: postgresql://root:password@postgres/course-portal-common?connect_timeout=300&pool_timeout=300
      RESTRICTED_DATABASE_URL: postgresql://root:password@postgres/course-portal-restricted?connect_timeout=300&pool_timeout=300

volumes:
  postgres: {}